 ### GET all students
GET http://localhost:4000/admin/students


### ADD company
POST http://localhost:4000/admin/add-company
Content-Type: application/json

{
    "companyName":"TCS",
    "minCGPA":7,
    "allowedBranches":["CSE","IT"],
    "package":"7 LPA",
    "driveDate":"2026-06-10"
}


### GET all companies
GET http://localhost:4000/admin/companies


### UPDATE company
PUT http://localhost:4000/admin/company/PASTE_COMPANY_ID_HERE
Content-Type: application/json

{
    "package":"9 LPA"
}


### DELETE company
DELETE http://localhost:4000/admin/company/PASTE_COMPANY_ID_HERE


### UPDATE student placement status
PATCH http://localhost:4000/admin/update-status/PASTE_STUDENT_ID_HERE
Content-Type: application/json

{
    "status":"Round 1 Cleared"
}

### UPDATE APPLICATION STATUS
PATCH http://localhost:4000/admin/update-status/PASTE_APPLICATION_ID
Content-Type: application/json

{
   "status":"Selected",
   "round":"HR Round"
}